<?php

namespace AppBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPendingReports()
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.status IS NULL')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getConfirmedReports()
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.status = true')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getDismissedReports()
    {
        $qb = $this->createQueryBuilder('r')
            ->andWhere('r.status = false')
        ;

        return $qb->getQuery()->getResult();
    }
}
