app:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app.register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }

# user
app.user.profile:
    path:     /profile
    defaults: { _controller: AppBundle:User:profile }
app.user.bookmarks:
    path:     /bookmarks
    defaults: { _controller: AppBundle:User:bookmarks }

# video
app.video:
    path:     /videos
    defaults: { _controller: AppBundle:Video:index }
app.video.create:
    path:     /videos/create
    defaults: { _controller: AppBundle:Video:create }
app.video.read:
    path:     /videos/{id}
    defaults: { _controller: AppBundle:Video:read }
    requirements:
        id: \d+

# category
app.category:
    path:     /categories
    defaults: { _controller: AppBundle:Category:index }
    requirements:
        id: \d+
app.category.read:
    path:     /categories/{id}
    defaults: { _controller: AppBundle:Category:read }
    requirements:
        id: \d+

# bookmark
app.bookmark.create:
    path:     /bookmarks/create/{video}
    defaults: { _controller: AppBundle:Bookmark:create }
app.bookmark.delete:
    path:     /bookmarks/delete/{video}
    defaults: { _controller: AppBundle:Bookmark:delete }

# security
app.security.login:
    path:   /login
    defaults:  { _controller: AppBundle:Security:login }

app.security.login_check:
    path:   /login_check

app.security.logout:
    path:   /logout
