<?php

namespace App\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActive()
    {
        $qb = $this->createQueryBuilder('v')
            ->andWhere('v.status = true')
        ;

        return $qb->getQuery()->getResult();
    }
}
