services:
    app.converter.video.uri_to_embed:
        class: AppBundle\Service\Converter\Video\UriToEmbedConverter

    app.listener.video:
        class: AppBundle\EventListener\VideoEventListener
        arguments:
            - "@app.converter.video.uri_to_embed"
        tags:
            - { name: kernel.event_listener, event: app.video_pre_save, method: preSave }

    # security
    app.security.encoder.password:
      class: AppBundle\Service\Encoder\PasswordEncoder

    app.security.listener.authentication:
        class: AppBundle\EventListener\AuthenticationListener
        arguments:
            - "@security.token_storage"
            - "@session"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
