services:
    app.converter.video.uri_to_embed:
        class: AppBundle\Service\Converter\Video\UriToEmbedConverter

    app.listener.video:
        class: AppBundle\EventListener\VideoEventListener
        arguments:
            - "@app.converter.video.uri_to_embed"
            - "@app.api.youtube_client"
        tags:
            - { name: kernel.event_listener, event: app.video_pre_save, method: preSave }

    app.api.youtube_client:
        class: AppBundle\Service\ApiClient\YoutubeApiClient
        arguments:
            - '%google_api_key%'

    # security
    app.security.encoder.password:
        class: AppBundle\Service\Encoder\PasswordEncoder

    # twig
    app.twig.extension:
        class: AppBundle\Twig\AppExtension
        arguments:
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
